version: '3.7'
services:
  redpanda:
    # NOTE: Please use the latest version here!
    image: docker.redpanda.com/vectorized/redpanda:v21.11.15
    container_name: redpanda
    command:
    - redpanda
    - start
    - --smp
    - '1'
    - --reserve-memory
    - 0M
    - --overprovisioned
    - --node-id
    - '1'
    - --kafka-addr
    - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
    - --advertise-kafka-addr
    - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    - --pandaproxy-addr
    - PLAINTEXT://0.0.0.0:28082,OUTSIDE://0.0.0.0:8082
    - --advertise-pandaproxy-addr
    - PLAINTEXT://redpanda:28082,OUTSIDE://localhost:8082
    ports:
    - 8081:8081
    - 8082:8082
    - 9092:9092
    - 28082:28082
    - 29092:29092

      #  broker:
      #    image: confluentinc/cp-kafka:7.0.1
      #    container_name: broker
      #    ports:
      #    # To learn about configuring Kafka for access across networks see
      #    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      #      - "9092:9092"
      #    depends_on:
      #      - zookeeper
      #    environment:
      #      KAFKA_BROKER_ID: 1
      #      KAFKA_ZOOKEEPER_CONNECT: 'redpanda:8081'
      #      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      #      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      #      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      #      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      #      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - /Users/duytc/Documents/Docker/Docker-data/Mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: duytc
    ports:
      - 3306:3306

