version: '3.1'
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      - /Users/duytc/Documents/Docker/Docker-data/Postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: duytc
    ports:
      - 5432:5432
